/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface BierActiveStrategies {}
  interface BierActiveStrategiesAttributes extends StencilHTMLAttributes {}

  interface BierAlternativeInvestments {}
  interface BierAlternativeInvestmentsAttributes extends StencilHTMLAttributes {}

  interface BierBasics {}
  interface BierBasicsAttributes extends StencilHTMLAttributes {}

  interface BierFooter {}
  interface BierFooterAttributes extends StencilHTMLAttributes {}

  interface BierHeader {
    'container': string;
  }
  interface BierHeaderAttributes extends StencilHTMLAttributes {
    'container'?: string;
  }

  interface BierHome {}
  interface BierHomeAttributes extends StencilHTMLAttributes {}

  interface BierPassiveStrategies {}
  interface BierPassiveStrategiesAttributes extends StencilHTMLAttributes {}

  interface BierRoot {}
  interface BierRootAttributes extends StencilHTMLAttributes {}

  interface BierSection {
    'heading': string;
    'image': string;
    'left': boolean;
  }
  interface BierSectionAttributes extends StencilHTMLAttributes {
    'heading'?: string;
    'image'?: string;
    'left'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BierActiveStrategies': Components.BierActiveStrategies;
    'BierAlternativeInvestments': Components.BierAlternativeInvestments;
    'BierBasics': Components.BierBasics;
    'BierFooter': Components.BierFooter;
    'BierHeader': Components.BierHeader;
    'BierHome': Components.BierHome;
    'BierPassiveStrategies': Components.BierPassiveStrategies;
    'BierRoot': Components.BierRoot;
    'BierSection': Components.BierSection;
  }

  interface StencilIntrinsicElements {
    'bier-active-strategies': Components.BierActiveStrategiesAttributes;
    'bier-alternative-investments': Components.BierAlternativeInvestmentsAttributes;
    'bier-basics': Components.BierBasicsAttributes;
    'bier-footer': Components.BierFooterAttributes;
    'bier-header': Components.BierHeaderAttributes;
    'bier-home': Components.BierHomeAttributes;
    'bier-passive-strategies': Components.BierPassiveStrategiesAttributes;
    'bier-root': Components.BierRootAttributes;
    'bier-section': Components.BierSectionAttributes;
  }


  interface HTMLBierActiveStrategiesElement extends Components.BierActiveStrategies, HTMLStencilElement {}
  var HTMLBierActiveStrategiesElement: {
    prototype: HTMLBierActiveStrategiesElement;
    new (): HTMLBierActiveStrategiesElement;
  };

  interface HTMLBierAlternativeInvestmentsElement extends Components.BierAlternativeInvestments, HTMLStencilElement {}
  var HTMLBierAlternativeInvestmentsElement: {
    prototype: HTMLBierAlternativeInvestmentsElement;
    new (): HTMLBierAlternativeInvestmentsElement;
  };

  interface HTMLBierBasicsElement extends Components.BierBasics, HTMLStencilElement {}
  var HTMLBierBasicsElement: {
    prototype: HTMLBierBasicsElement;
    new (): HTMLBierBasicsElement;
  };

  interface HTMLBierFooterElement extends Components.BierFooter, HTMLStencilElement {}
  var HTMLBierFooterElement: {
    prototype: HTMLBierFooterElement;
    new (): HTMLBierFooterElement;
  };

  interface HTMLBierHeaderElement extends Components.BierHeader, HTMLStencilElement {}
  var HTMLBierHeaderElement: {
    prototype: HTMLBierHeaderElement;
    new (): HTMLBierHeaderElement;
  };

  interface HTMLBierHomeElement extends Components.BierHome, HTMLStencilElement {}
  var HTMLBierHomeElement: {
    prototype: HTMLBierHomeElement;
    new (): HTMLBierHomeElement;
  };

  interface HTMLBierPassiveStrategiesElement extends Components.BierPassiveStrategies, HTMLStencilElement {}
  var HTMLBierPassiveStrategiesElement: {
    prototype: HTMLBierPassiveStrategiesElement;
    new (): HTMLBierPassiveStrategiesElement;
  };

  interface HTMLBierRootElement extends Components.BierRoot, HTMLStencilElement {}
  var HTMLBierRootElement: {
    prototype: HTMLBierRootElement;
    new (): HTMLBierRootElement;
  };

  interface HTMLBierSectionElement extends Components.BierSection, HTMLStencilElement {}
  var HTMLBierSectionElement: {
    prototype: HTMLBierSectionElement;
    new (): HTMLBierSectionElement;
  };

  interface HTMLElementTagNameMap {
    'bier-active-strategies': HTMLBierActiveStrategiesElement
    'bier-alternative-investments': HTMLBierAlternativeInvestmentsElement
    'bier-basics': HTMLBierBasicsElement
    'bier-footer': HTMLBierFooterElement
    'bier-header': HTMLBierHeaderElement
    'bier-home': HTMLBierHomeElement
    'bier-passive-strategies': HTMLBierPassiveStrategiesElement
    'bier-root': HTMLBierRootElement
    'bier-section': HTMLBierSectionElement
  }

  interface ElementTagNameMap {
    'bier-active-strategies': HTMLBierActiveStrategiesElement;
    'bier-alternative-investments': HTMLBierAlternativeInvestmentsElement;
    'bier-basics': HTMLBierBasicsElement;
    'bier-footer': HTMLBierFooterElement;
    'bier-header': HTMLBierHeaderElement;
    'bier-home': HTMLBierHomeElement;
    'bier-passive-strategies': HTMLBierPassiveStrategiesElement;
    'bier-root': HTMLBierRootElement;
    'bier-section': HTMLBierSectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
